.github/workflows/github_actions.yml
README.md
irc_responses.py
mantatail.py
requirements-dev.txt
tests/test_mantatail.py

@Akuli I pushed what I have so you have the chance to debug if you get the time.
Todo list (feel free to edit):

Start working on tests

---

mantatail.py
tests/test_mantatail.py

Implement logic to make mantatail work with netcat

---

.github/workflows/github_actions.yml
README.md
mantatail.py
requirements-dev.txt

This is the same tool that Porcupine uses internally for displaying red and yellow underlines in code. It warns about unnecessary imports, potentially undefined variables, and a few other things
I switched the order of the if,else statement in `recv_loop()` to make pyflakes happy. It "reads" the code from top to bottom, and assumes everything is defined before (i.e. above) it is used.

add pyflakes linter

---

.github/workflows/github_actions.yml
README.md

Add separate tests for different platforms

---

mantatail.py
tests/test_mantatail.py

Stop connection close on unknown command

---

mantatail.py
tests/test_mantatail.py

Add thread lock for part channel

---

command.py
mantatail.py
tests/test_mantatail.py

We aren't sure yet whether any of this is a good idea.

split Server into Listener and ServerState

---

command.py
mantatail.py

Duplicate of #43 without merge conflicts from main
Fixes #41

Move thread lock

---

commands.py
mantatail.py
tests/test_mantatail.py

Use latin-1 internally, so that messages work with any encoding

---

commands.py
mantatail.py
tests/test_mantatail.py

Fix user prefix not showing on self when joining channel

---

commands.py
irc_responses.py
mantatail.py
tests/test_mantatail.py

An error arose in `find_user()` and `find_channel()` when adding the test for private message error.
That's why they are changed.
Everything else seems to work properly. See if any mantaray tests that used to fail now pass

Add logic for sending private message to user

---

commands.py
tests/test_mantatail.py

Fix prefix when setting channel mode

---

commands.py
irc_responses.py
mantatail.py
tests/test_mantatail.py

Issue hunt1

---

commands.py
tests/test_mantatail.py

Issue hunt2

---

commands.py
tests/test_mantatail.py

Fixes #68 
I found the bug with `git grep strip`, and I added a new test that fails every time on main.

Fix messages starting with :

---

commands.py
tests/test_mantatail.py

Issue hunt3

---

commands.py
tests/test_mantatail.py

Issue hunt4

---

mantatail.py
tests/test_mantatail.py

Fix not enough params error for USER

---

tests/fuzzer/fuzzer.py

I think this makes the fuzzer as user friendly as it will ever have to be.

fuzzer start print

---

commands.py
irc_responses.py
mantatail.py
tests/fuzzer/fuzzer.py
tests/test_mantatail.py

This PR implements the logic for channel topics.
- Test has been added.
- Topic keyword has been added to fuzzer.
- I get no errors when running the fuzzer between 30sec to 1 min

Channel topic

---

commands.py
irc_responses.py
mantatail.py
tests/fuzzer/fuzzer.py
tests/test_mantatail.py

Away functionality based on Libera.

Away status

---

.github/workflows/github_actions.yml

This should make it easier to see why a test errored

Run pytest with -vv

---

server.py

Tested manually with two computers.

Listen to connections coming from other computers within the same network

---

server.py

update PING and PONG timers
